### ISSUE TITLE
any support for windows or macos application?

### ISSUE THREAD

**Issue by kechankrisna** [pusher/pusher-channels-flutter#103]
any support for windows or macos application?

**Comment by benw-pusher** [comment]
This library support iOS, Android and web. You may be able to use the web support (JS) if your app uses this language. If you are looking to create a native Windows app we do have other libraries that may achieve this, for example dotnet and swift. You can find a full list of the libraries at https://pusher.com/docs/channels/channels_libraries/libraries/

**Comment by kechankrisna** [comment]
> This library support iOS, Android and web. You may be able to use the web support (JS) if your app uses this language. If you are looking to create a native Windows app we do have other libraries that may achieve this, for example dotnet and swift. You can find a full list of the libraries at https://pusher.com/docs/channels/channels_libraries/libraries/

It is good if you ship the existing cpp++ libraries for flutter windows and swift for flutter macos, because this process take some times to complete.

**Comment by benw-pusher** [comment]
Thanks for the feedback, I will share this internally for consideration in the future - however we can't commit to shipping these libraries at this time.

**Comment by EwertonDutra** [comment]
No update to have the sdk for windows yet (using flutter)?

If not, is there any way in Flutter on Windows to "listen" to pusher events?

Att
