### ISSUE TITLE
pusher-java-client eventQueue

### ISSUE THREAD

**Issue by AbdallahMohamed220** [pusher/pusher-channels-flutter#106]
E/AndroidRuntime(13063): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime(13063): Process: com.example.fix_infinity, PID: 13063
E/AndroidRuntime(13063): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pusher.client.channel.impl.message.AuthResponse.getChannelData()' on a null object reference
E/AndroidRuntime(13063): 	at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:84)
E/AndroidRuntime(13063): 	at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:101)
E/AndroidRuntime(13063): 	at com.pusher.client.channel.impl.PresenceChannelImpl.toSubscribeMessage(PresenceChannelImpl.java:78)
E/AndroidRuntime(13063): 	at com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0$com-pusher-client-channel-impl-ChannelManager(ChannelManager.java:134)
E/AndroidRuntime(13063): 	at com.pusher.client.channel.impl.ChannelManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(13063): 	at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
E/AndroidRuntime(13063): 	at com.pusher.client.util.Factory$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(13063): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(13063): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(13063): 	at java.lang.Thread.run(Thread.java:764)

**Comment by benw-pusher** [comment]
Could you share the code used when this was encountered?

**Comment by AbdllahMohamed** [comment]
@override
  void initState() {
    super.initState();
    initConnection();
  }

  void initConnection() async {
    try {
      await pusher.init(
        apiKey: '81ds955css4b9f5ddd52e664a4',
        cluster: 'mt1',
        onConnectionStateChange: onConnectionStateChange,
        onError: onError,
        onSubscriptionSucceeded: onSubscriptionSucceeded,
        onEvent: onEvent,
        onSubscriptionError: onSubscriptionError,
        onDecryptionFailure: onDecryptionFailure,
        onMemberAdded: onMemberAdded,
        onMemberRemoved: onMemberRemoved,
        onSubscriptionCount: onSubscriptionCount,
        authEndpoint: "$baseurl/broadcasting/auth",
         onAuthorizer: onAuthorizer,
         authParams: {
          'headers': {'Authorization': '${CacheHelper.getData(key: 'token')}'}
        },
      );
      await pusher.subscribe(channelName: 'presence-chat.${widget.orderId}');

      await pusher.connect();
    } catch (e) {
      log("ERROR: $e");
    }
  }

**Comment by OmarYehiaDev** [comment]
Anything new about this?

**Comment by AbdllahMohamed** [comment]
I didn't find answer so I use this packages :

**Comment by OmarYehiaDev** [comment]
And did it work? I don't know Laravel_echo but pusher_client is supposed to be discontinued :(

**Comment by AbdllahMohamed** [comment]
it work work with me and if you need I can send post configuration

**Comment by OmarYehiaDev** [comment]
Okay, please if you can, share with me the code as a gist or a repo
You can send it over to my mail if you can't share it publicly

mail: omaryahiatawfiek@gmail.com

**Comment by AbdllahMohamed** [comment]
very sorry for my late response here is my initstate for configure pusher  
all data below you can ask backend for it if you have any problem you can send me email to : dev.fluttery@gmail.com 
and we can have meeting to check the problem     

 
late PusherClient pusherClient;
  @override
  void initState() {
    super.initState();



    PusherOptions options = PusherOptions(
      cluster: 'set here cluster name',
      auth: PusherAuth(
        'ser here api endpoint for auth',
        headers: {
          'Authorization': 'Bearer $token',
        },
      ),
    );

    pusherClient = PusherClient(
      'here put app id',
      options,
      autoConnect: false,
      enableLogging: true,
    );

    pusherClient.subscribe('set her channel name');

    Echo echo = Echo(
      client: pusherClient,
    );

    echo.channel(''}').listen('NewMessageSent',
        (e) {
      Map<String, dynamic> data = json.decode(jsonEncode(e));



    });

  }

**Comment by benjamin-tang-pusher** [comment]
I've you're getting this error every time, we've seen in the past NullPointerException on AuthResponse.getChannelData() is because of an incorrect auth response from your backend that isn't handled well by our library. Could you provide yours?

**Comment by benw-pusher** [comment]
We haven't had a response here so closing. If you need further support please get in touch with us via https://messagebird.com/support-center/Pusher-request-new
