### ISSUE TITLE
Subscribe to private channel from ios not working

### ISSUE THREAD

**Issue by ShehanYjoz** [pusher/pusher-channels-flutter#108]
[log] Event received channel: { channelName: private-chat-YU12390-YU48094, eventName: pusher:subscription_error, data: , userId: null }

this because of onAuthorizer () callback not calling.  But android working fine

**Comment by Shahmirzali-Huseynov** [comment]
how did you solve I didn't get? you removed authEndpoint from init but added where? cause authEndpoint is required can you help ? @ShehanYjoz

**Comment by ShehanYjoz** [comment]
```
      onAuthorizer:
            (String channelName, String socketId, dynamic options) async {
          log("inside onAuthorizer");
          return await userRemoteDataSource.authPusher(
              channelName: channelName, socketId: socketId);
        },
```


use onAuthorizer and return 

[POST Response: pusher_auth] {"auth":"43b29e235cc21668XXXX:XXXX13c52bf54c78e22f1b7c5b9aae0baca1a6087264411bbb489c6df48XXXXX"}


from your server
