### ISSUE TITLE
Unable to find a specification for `PusherSwift (~> 10.1.1)

### ISSUE THREAD

**Issue by lampian** [pusher/pusher-channels-flutter#110]
Compiling flutter project with pusher_channels_flutter: ^2.1.2 the following error:
[!] Unable to find a specification for `PusherSwift (~> 10.1.1)` depended upon by `pusher_channels_flutter`
    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

Using environment:
flutter 3.7.7
Xcode 14.2
iOS target  13.0 

Have tried pod repo update and pod install --repo-update

Kindly provide suggestions how to remedy this as it is blocking iOS development

**Comment by benw-pusher** [comment]
Are you able to share your podfile.lock for review?

**Comment by lampian** [comment]
Issue resolved.
The apps' iOS pod file required a source file to a custom package which caused the pod not to be found.
Adding source 'https://github.com/CocoaPods/Specs.git' to the app pod file resolved the issue. 
Most probably not the best solution to the issue, but at least it removed the blocker so that I can continue evaluating Pusher for our application.

**Comment by benw-pusher** [comment]
Thanks for sharing. Do you then receive any errors when you run 'pod repo update'? I know you mentioned you have already run this, but it seems the repo is still out of date according to this error.
