### ISSUE TITLE
Pusher Channels Flutter not working on iOS devices

### ISSUE THREAD

**Issue by mohamedsalah414** [pusher/pusher-channels-flutter#115]
It's working perfectly fine on Android devices, but I'm running into issues when testing on iOS devices. Specifically, the real-time communication feature doesn't seem to be working on iOS devices.

And I already did it
iOS specific installation [#](https://pub.dev/packages/pusher_channels_flutter#ios-specific-installation)
The Pusher Channels Flutter plugin adds the pusher-websocket-swift cocoapod to your project. You probably need to run a

`$ pod install`
in the ios directory.

and this is my podfile.lock

```swift
  - pusher_channels_flutter (0.0.1):
    - Flutter
    - PusherSwift (~> 10.1.1)
  - PusherSwift (10.1.3):
    - NWWebSocket (~> 0.5.3)
    - TweetNacl (~> 1.0.0)
```

**Comment by Zain-Waheed** [comment]
I am also running into the same issue and have not solved it yet

**Comment by mohamedsalah414** [comment]
I've been trying to integrate PusherSwift into my Xcode project using both Cocoapods and Carthage, but I'm encountering an issue. Here are the steps I've taken so far:

1. I have the Cocoapods gem installed on my machine.
2. In my Podfile, I added the line `pod 'PusherSwift'`.
3. To update PusherSwift, I ran the following commands:
   ```
   $ pod repo update PusherSwift
   $ pod install
   ```
4. Additionally, I integrated PusherSwift using Carthage in my project.
5. I specified the desired iOS version by adding `platform :ios, '14.0'` to my Podfile.

Despite following these steps, I'm still facing the same issue. The problem persists even after updating and installing PusherSwift. I would greatly appreciate any guidance you can provide to help resolve this issue.

**Comment by mohamedsalah414** [comment]
### Remove `authEndpoint: url` from the `init` function as it's only used in the web version, causing issues on iOS.

```dart
 await pusher.init(
        apiKey: 'f****************',
        cluster: 'eu',
        onConnectionStateChange: onConnectionStateChange,
        onError: onError,
        onSubscriptionSucceeded: onSubscriptionSucceeded,
        onEvent: onEvent,
        onSubscriptionError: onSubscriptionError,
        onDecryptionFailure: onDecryptionFailure,
        onMemberAdded: onMemberAdded,
        onMemberRemoved: onMemberRemoved,

        // authEndpoint: "<Your Authendpoint Url>",  Just delete this line
        
        onAuthorizer: onAuthorizer,
      );
```

**Comment by en-roshdy** [comment]
i had the same issue, 
for me I just updated platform :ios, '12.0' to platform :ios, '13.0' in podfile
