### ISSUE TITLE
Flutter pusher works in Android but not in IOS

### ISSUE THREAD

**Issue by Zain-Waheed** [pusher/pusher-channels-flutter#118]
Working well on Android devices but not on IOS . On IOS it only connect to the pusher but not able to subscribe to a private channel. Do all the things and try again and again but  the issue is still remain there.

**Comment by Zain-Waheed** [comment]
@mohamedsalah414  Thankyou so much now it is working and continue to subscribe to the private channels.That was a big fix for me.

**Comment by Shahmirzali-Huseynov** [comment]
@mohamedsalah414  but how can I define authEndpoint cause it's required for connection private channel ?

**Comment by benjamin-tang-pusher** [comment]
@Shahmirzali-Huseynov you can try implementing your own a POST request to your auth backend in your [onAuthorizer method](https://github.com/pusher/pusher-channels-flutter#onauthorizer), returning the necessary keys.

However I can't reproduce the the iOS app not hitting the auth endpoint with the auth request. Are you both using the latest 2.2.0 version of our flutter library? Does your auth endpoint receive the auth request from your flutter client?

**Comment by Shahmirzali-Huseynov** [comment]
@benjamin-tang-pusherthanks for your reply. But I solved the issue, but for now I'm using different package, cause my socket is self-hosted.
