### ISSUE TITLE
error Thread1: signal SIGABRT

### ISSUE THREAD

**Issue by joselcv** [pusher/pusher-channels-flutter#119]
public func fetchAuthValue(socketID: String, channelName: String, completionHandler: @escaping (PusherAuth?) -> Void) {
    methodChannel!.invokeMethod("onAuthorizer", arguments: [
      "socketId": socketID,
      "channelName": channelName,
    ]) { authData in
      if authData != nil {
        let authDataCast = authData as! [String: String]   
        completionHandler(
          PusherAuth(
            auth: authDataCast["auth"]!,
            channelData: authDataCast["channel_data"],
            sharedSecret: authDataCast["shared_secret"]
          ))
      } else {
        completionHandler(nil)
      }
    }
  }

I am trying to use the package but this error appears in the quick part, apparently they are trying to indicate that they are trying to convert an object of type FlutterError to an object of type NSDictionary

**Comment by gabrielginter** [comment]
@joselcv I was experiencing a similar crash, if not the same. For what I can tell from your message, you have an `onAuthorizer` method set up. Make sure that method is not returning NULL or throwing an exception (perhaps on network disconnect).

After adding error management to my `onAuthorizer` method and returning an empty JSON `{"auth":""}` if I'm not able to recover from the errors, the crash went away completely.

I hope it helps.

**Comment by benw-pusher** [comment]
@gabrielginter solution should resolve this issue. If you need anything more please get in touch at https://messagebird.com/support-center/Pusher-request-new
