### ISSUE TITLE
Binding to a specific event

### ISSUE THREAD

**Issue by mbebs** [pusher/pusher-channels-flutter#126]
The code specifies binding to any event under the channel. e.g 

```
final myChannel = await pusher.subscribe(
  channelName: "my-channel",
  onEvent: (event) {
    print("Got channel event: $event");
  }
);
```

What if i have a specific event "my-event" under channel "my-channel" i want to bind to? Where do i specify the event name?

**Comment by benjamin-tang-pusher** [comment]
You will need to do a filter the event name yourself. For example:

```
void onEvent(PusherEvent event) {
    if (event.eventName.compareTo("event1") == 0) {
      log("event1 logged");
    } else {
      log("some other event: $event");
    }
  }
```
Unfortunately this library doesn't do the event name filtering like our other libraries due to its design.

**Comment by benjamin-tang-pusher** [comment]
I will close this due to no further responses.
