### ISSUE TITLE
Incompatible classes were found in dependencies

### ISSUE THREAD

**Issue by gordett** [pusher/pusher-channels-flutter#128]
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/gordett/.gradle/caches/transforms-3/0c41a6abb3097408b1800d57ac9f5d0e/transformed/jetified-kotlin-stdlib-jdk7-1.7.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/gordett/.gradle/caches/transforms-3/3f5150167d031532b451b4440175f6a4/transformed/jetified-kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/gordett/.gradle/caches/transforms-3/866c12a1a814a0d8ab123e090442ad11/transformed/jetified-kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/gordett/.pub-cache/hosted/pub.dev/pusher_channels_flutter-2.2.0/android/src/main/kotlin/com/pusher/channels_flutter/PusherChannelsFlutterPlugin.kt: (35, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/gordett/.gradle/caches/transforms-3/3f5150167d031532b451b4440175f6a4/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/gordett/.pub-cache/hosted/pub.dev/pusher_channels_flutter-2.2.0/android/src/main/kotlin/com/pusher/channels_flutter/PusherChannelsFlutterPlugin.kt: (40, 23): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/gordett/.gradle/caches/transforms-3/3f5150167d031532b451b4440175f6a4/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class

**Comment by benjamin-tang-pusher** [comment]
I'm also using `ext.kotlin_version = '1.7.10'` in my project and it builds ok. Do you have the following in your build.gradle?

```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

If not, can you try again in a new Flutter project with a recent version of Flutter?

**Comment by benw-pusher** [comment]
We haven't had a response here so closing.
