### ISSUE TITLE
FATAL EXCEPTION on subscription attempt

### ISSUE THREAD

**Issue by 1mavic** [pusher/pusher-channels-flutter#13]
Tying to subscribe on **public** channel.
on Android getting exception.
E[/AndroidRuntime]()( 4380): Process: com.example.flutter_application_1, PID: 4380
E[/AndroidRuntime]()( 4380): java.lang.IllegalArgumentException: Presence channels must begin with 'presence-'
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.channel.impl.ChannelManager.getPresenceChannel(ChannelManager.java:60)
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.Pusher.getPresenceChannel(Pusher.java:418)
E[/AndroidRuntime]()( 4380): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin$SubChannelManager.onMessage(PusherChannelsFlutterPlugin.kt:42)
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:177)
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:27)
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:261)
E[/AndroidRuntime]()( 4380): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
E[/AndroidRuntime]()( 4380): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E[/AndroidRuntime]()( 4380): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E[/AndroidRuntime]()( 4380): 	at java.lang.Thread.run(Thread.java:923)

pusher.init(
              apiKey: 'xxxxxxxxxxxx',
              cluster: 'xx',
            );
await pusher.subscribe(channelName: 'test1', onEvent: (e){print("onEvent: $e");});
await pusher.connect();

**Comment by Frogperson** [comment]
Looks like this may have been fixed in #11
