### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "pusher_channels_flutter"

### ISSUE THREAD

**Issue by yishaq06** [pusher/pusher-channels-flutter#131]
Analyzing dependencies
firebase_core: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.12.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "pusher_channels_flutter":
  In Podfile:
    pusher_channels_flutter (from `.symlinks/plugins/pusher_channels_flutter/ios`)

Specs satisfying the `pusher_channels_flutter (from `.symlinks/plugins/pusher_channels_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by pishguy** [comment]
+1

pusher_channels_flutter: ^2.2.0

```
[!] CocoaPods could not find compatible versions for pod "pusher_channels_flutter":
  In Podfile:
    pusher_channels_flutter (from `.symlinks/plugins/pusher_channels_flutter/ios`)

Specs satisfying the `pusher_channels_flutter (from `.symlinks/plugins/pusher_channels_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.
```
