### ISSUE TITLE
[Android] [Foreground service] getting java.lang.NullPointerException

### ISSUE THREAD

**Issue by tharakasandun** [pusher/pusher-channels-flutter#133]
I get this issue when I try to initialize via Flutter foreground service.

`I/PusherChannelsFlutter(12549): Pusher authorize error: java.lang.NullPointerException`

Pub version: 2.2.0

Note : 
In IOS Pusher can initialize without any error.

In Android, `pusher.init` method throws the above error without calling `onAuthorizer` method.
`onAuthorizer` method never hits the debug point.

**Comment by Ilthizam** [comment]
Facing the same issue

**Comment by benw-pusher** [comment]
I believe you also raised a support ticket with us regarding this but this has auto-closed as we haven't received a response. Please get in touch with us via support@pusher.com if you need further assistance.
