### ISSUE TITLE
Can't Subscribe to a Private Channel on Web, Cookie Mismatch

### ISSUE THREAD

**Issue by coogle** [pusher/pusher-channels-flutter#135]
Hello,

I'm trying to get this to work with a Laravel backend (Flutter Web) on a private channel which is uses a cookie in the backend to maintain authentication. When I just tried to point `authEndpoint` to the correct URL to validate that the user has access to a given channel my backend returns a 401 because the cookie being provided doesn't match the correct cookie. This leads me to the conclusion that Pusher is using some sort of separate HTTP client under the hood that is maintaining its own session state.

I have tried everything I can think of to override the HTTP request here, so I can inject my own request to make sure the cookie values are properly managed and I can't do it.

Is there any way to override the default behavior for the client when requesting authorization?

**Comment by coogle** [comment]
To add to this..

Trying to get past this bug I decided it made sense anyway for me to provide a way to authenticate API requests (and thus private channels) using a simple `Authorization` header. I've implemented that solution and I attempted to get it working with this code base with no success:

```dart
        await client.init(
            apiKey: _apiKey,
            cluster: _apiCluster,
            onConnectionStateChange: _onConnectionStateChange,
            onError: _onError,
            logToConsole: logToConsole,
            onSubscriptionSucceeded: _onSubscriptionSucceeded,
            onEvent: _onEvent,
            onSubscriptionError: _onSubscriptionError,
            onDecryptionFailure: _onDecryptionFailure,
            onMemberAdded: _onMemberAdded,
            onMemberRemoved: _onMemberRemoved,
            authEndpoint: authEndpoint,
            authParams: {
                'params' : {},
                'headers': {
                    'Authorization' : 'Bearer ' + _currentUser.api_token
                }
            },
            onSubscriptionCount: _onSubscriptionCount,
        );
  ```
  
 When this code is executed I get an exception:
 
 ```
 Error: PlatformException(error, Expected a value of type 'AuthOptions', but got one of type
'LinkedMap<Object?, Object?>', null, null)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/flutter/src/services/message_codecs.dart 652:7                       decodeEnvelope
packages/flutter/src/services/platform_channel.dart 310:18                    _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 156:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 840:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 869:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 641:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 715:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>
```

Further, I have also attempted to use `onAuthorizer` (both with and without `authEndpoint`) to build my own authorization request and provide the response. As far as I can tell, I have seen no evidence this method is called under any circumstances. 

Unless I am missing something really obvious, it seems that this package is broken entirely for private channels. Please help!

**Comment by benw-pusher** [comment]
I'm not entirely certain why you are encountering the `Expected a value of type 'AuthOptions` error, but to achieve what you are looking for you need to use `onAuthorizer` (without the `authEndpoint` param defined) so I think it makes sense to troubleshoot this setup. 
Can you share the implementation of this approach?

**Comment by benw-pusher** [comment]
Closing as we haven't had a response here. 
If you need more support please get in touch at https://messagebird.com/support-center/Pusher-request-new

**Comment by benw-pusher** [comment]
Closing as we haven't had a response here. 
If you need more support please get in touch at https://messagebird.com/support-center/Pusher-request-new
