### ISSUE TITLE
Error: Dart library 'dart:js' is not available on this platform

### ISSUE THREAD

**Issue by EmilioMirasola** [pusher/pusher-channels-flutter#142]
Hi,

I'm experimenting with Pusher in my Flutter app.
When I try to run it on an Android device, I get the following error: Error: Dart library 'dart:js' is not available on this platform.
I see that dart:js is imported by the pusher_channels_flutter package.  How can this be fixed?

**Comment by EmilioMirasola** [comment]
Lol.. my bad.. turns out I had some crazy weird import statement from your library hidden in a file elsewhere which caused the problem.

**Comment by atoruliahotshotslabs** [comment]
God bless you, man. 6 hours of searching for the problem, I even reinstalled Flutter. Turns out I had the wrong import. Without your reply, I would have never noticed that import
