### ISSUE TITLE
Laravel Reverb

### ISSUE THREAD

**Issue by n4ff4h** [pusher/pusher-channels-flutter#158]
Hi, does this work with Laravel Reverb?

**Comment by mstfkhazaal** [comment]
Not yet, i tried but the package need the cluster is required

**Comment by mstfkhazaal** [comment]
> > Not yet, i tried but the package need the cluster is required
> 
> Ahh ok thanks.

You can use this package 
https://pub.dev/packages/dart_pusher_channels

**Comment by KhaledKhlefAlabdullah** [comment]
can you helpe i tray to do it but its dont work
