### ISSUE TITLE
failed to build apk

### ISSUE THREAD

**Issue by nandamodjo21** [pusher/pusher-channels-flutter#168]
What went wrong:
Execution failed for task ':pusher_channels_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: D:\reborn\csaiapp\build\pusher_channels_flutter\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

**Comment by Hassan6197** [comment]
Go to /Users/YOUR_NAME/.pub-cache/hosted/pub.dev/pusher_channels_flutter-2.2.1/android/build.gradle. In the build.gradle upgrade compileSdkVersion to 34
