### ISSUE TITLE
Need feature to bind an event of a particular channel 

### ISSUE THREAD

**Issue by tarafat** [pusher/pusher-channels-flutter#183]
I can't bind to a specific event of a channel.
Is it possible to bind an event from a particular channel using a pusher in Flutter?
like this:
https://youtu.be/ot4jyrXyKCo?si=bWQpH3-s1tArTzI5

I have seen a closed issue "Binding to a specific event #126",
can we make a solution to it now?

**Comment by evgeniibreikin** [comment]
Hey @tarafat no, you can handle event name inside onEvent callback, just like in the https://github.com/pusher/pusher-channels-flutter/issues/126 comment
