### ISSUE TITLE
How can i connect to a subscription in GraphQL?

### ISSUE THREAD

**Issue by julianramoscalvo** [pusher/pusher-channels-flutter#22]
I don't know how to do that, i would like to connect with a pusher and to have a listener to a graphQL subscription.  Something like this -> `pusherClient
  .subscribe({
    query: gql
    subscription {
      shipmentUpdated {
             id
              uuid
              tracking_number
      }
    }
  }).subscribe((result) => {
    this.addShipmentUpdated(result.data.shipmentUpdated)
  })`

**Comment by benw-pusher** [comment]
This is not possible with this library. This library is intended for use with [Pusher Channels](https://pusher.com/docs/channels/) and can receive events sent using our service but it cannot subscribe to GraphQL subscriptions.
