### ISSUE TITLE
Add Bearer Token to header for authorization endpoint for private and presence channels

### ISSUE THREAD

**Issue by solpreneur** [pusher/pusher-channels-flutter#25]
I am trying to add a bearer token to the header when requesting authorization from a custom endpoint on the server but can't seem to get this to work. (Android & IOS)
I used the example code on flutter, i couldn't add any information to the header sent to my auth server. 

According to the docs this is the only info i could find the relates. I might be missing something. 

```
//When passing the onAuthorizer() callback to the init() method, this callback is called to request auth information. For more information on how to generate the correct information, please look here:

  dynamic onAuthorizer(String channelName, String socketId, dynamic options) {
    return {
      "auth": "foo:bar",
      "channel_data": '{"user_id": 1}',
      "shared_secret": "foobar"
      
    };
  }
```

**Comment by fbenevides** [comment]
We still don't support custom headers on the authorization process for Android and iOS, just for Web.

**Comment by proggen-com** [comment]
Can you please look at https://github.com/pusher/pusher-channels-flutter/issues/9#issuecomment-1063969562  for a custom authorizer that could be modified to your needs?

**Comment by solpreneur** [comment]
Thanks I will have a look at this.

**Comment by solpreneur** [comment]
> 

I tried the idea from [ #9 (comment)](https://github.com/pusher/pusher-channels-flutter/issues/9#issuecomment-1063969562) but unfortunately it didn't work for me. I still couldn't add extra header info.

**Comment by JordanDalton** [comment]
+1 for this request

**Comment by JordanDalton** [comment]
> 

I got onAuthorizer to work for my situation.

**Comment by solpreneur** [comment]
Please could you let me know how you made it work ? still can't get the bearer token in there. I get the request at the server but not way to auth because i need the bearer token.

```
dynamic onAuthorizer(
      String channelName, String socketId, dynamic options) async {
    var authUrl = baseUrl + '/broadcasting/auth';
    var result = await post(
      Uri.parse(authUrl),
      headers: {
         'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'Bearer ${V.instance.apiToken}',
      },
      body: 'socket_id=' + socketId + '&channel_name=' + channelName,
    );
    return jsonDecode(result.body);
  }
```

**Comment by solpreneur** [comment]
i was able to get the onAuthorizer to work, apparently adding "**authEndpoint**" option when initializing will **prevent** pusher for **calling** the **onAuthorizer** method.

**Comment by JordanDalton** [comment]
> Please could you let me know how you made it work ? still can't get the bearer token in there. I get the request at the server but not way to auth because i need the bearer token.
> 
> ```
> dynamic onAuthorizer(
>       String channelName, String socketId, dynamic options) async {
>     var authUrl = baseUrl + '/broadcasting/auth';
>     var result = await post(
>       Uri.parse(authUrl),
>       headers: {
>          'Content-Type': 'application/x-www-form-urlencoded',
>         'Authorization': 'Bearer ${V.instance.apiToken}',
>       },
>       body: 'socket_id=' + socketId + '&channel_name=' + channelName,
>     );
>     return jsonDecode(result.body);
>   }
> ```

I ended up working only for public channels.
