### ISSUE TITLE
Build fails on Android with missing file error

### ISSUE THREAD

**Issue by rutvik110** [pusher/pusher-channels-flutter#27]
**Description:**

I'm using the `v1.0.2` of the plugin and flutter `v2.8.0`.  After adding it as a dependancy, app fails to build on **Android**. It's looking for the file containing `ConnectionEventListener ` but is not able to find it as it shows in the error logs below.
The issue also occurs with the older versions.

**Error logs :**

```
Running "flutter pub get" in chaseapp...
[/Users/rutviktak/flutter_projects/chaseApp/chaseapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:154](): error: cannot access ConnectionEventListener
      flutterEngine.getPlugins().add(new com.pusher.channels_flutter.PusherChannelsFlutterPlugin());
                                ^
  class file for com.pusher.client.connection.ConnectionEventListener not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 1m 41s




```

**How to reproduce?**  :

1. Create a new flutter project.
2. Add the dependancy.
3. Try building the app.

**Comment by rutvik110** [comment]
I was able to resolve the issue by adding the pusher java client dependancy in the **app level build.gradle** file.
```
dependencies {
    ...
    implementation 'com.pusher:pusher-java-client:2.2.8'
}
```
Though I had to do it explicitely unlike it's mentioned in the documentation on pub.dev, that it'll be added automatically. And neither the documentation on website for Flutter integration specify this.
<img width="788" alt="Screenshot 2022-02-22 at 7 02 10 PM" src="https://user-images.githubusercontent.com/65209850/155142461-7a4a84a5-aa97-4e71-b428-a2563e0abc7b.png">

At this point, the build issue is no longer there but it's now about updating the documentation to reflect this. Will wait for the responce before closing this issue.

**Comment by SORNVENGE** [comment]
> I was able to resolve the issue by adding the pusher java client dependancy in the **app level build.gradle** file.
> 
> ```
> dependencies {
>     ...
>     implementation 'com.pusher:pusher-java-client:2.2.8'
> }
> ```
> 
> Though I had to do it explicitely unlike it's mentioned in the documentation on pub.dev, that it'll be included automatically. And neither the documentation on the official website for Flutter integration specify this. <img alt="Screenshot 2022-02-22 at 7 02 10 PM" width="788" src="https://user-images.githubusercontent.com/65209850/155142461-7a4a84a5-aa97-4e71-b428-a2563e0abc7b.png">
> 
> At this point, the build issue is no longer there but it's now about updating the documentation to reflect this. Will wait for the responce before closing this issue.

It really working well after add this one, thanks you so much dear

**Comment by benjamin-tang-pusher** [comment]
I can reproduce this, let me check with the team if there's something wrong here, as flutter pub add should already do this.

**Comment by benjamin-tang-pusher** [comment]
This will be fixed in https://github.com/pusher/pusher-channels-flutter/pull/30
