### ISSUE TITLE
Android not receiving messages

### ISSUE THREAD

**Issue by barees63** [pusher/pusher-channels-flutter#31]
Hi there, the package is working fine on iOS but on Android I can subscribe and unsubscribe to a private channel (and I see these events in the Pusher.com debug console), but `onSubscriptionSucceeded` is never called and I don't receive messages.

I did have to manually add `implementation 'com.pusher:pusher-java-client:2.2.8'` as it was missing.

There are no exceptions being thrown and no errors in logcat.

I'm seeing the same behavior on emulator and physical device.

What can I provide to help resolve this?  Given that it works fine on iOS I don't imagine it's my implementation?

**Comment by benjamin-tang-pusher** [comment]
Hi, can you try again on our new version of the flutter library, and remove the manual implementation 'com.pusher:pusher-java-client:2.2.8' from your gradle file?

**Comment by smalik02** [comment]
Hi - any updates on this? It definitely doesn't seem to be working with v1.0.4 and the included manual implementation. iOS has no issues.

**Comment by proggen-com** [comment]
I can confirm the issue and will create a pull request with a fix today.

**Comment by rafaellkf** [comment]
For me it's working, now i'm getting the events.

**Comment by smalik02** [comment]
It's working well now.

**Comment by ali-raza-flutter** [comment]
v1.0.5 fixed this issue for me too.

**Comment by proggen-com** [comment]
Thanks I'm closing this issue.
