### ISSUE TITLE
How to authenticate to Laravel+Pusher+Echo backend and listen a private channel?

### ISSUE THREAD

**Issue by gtu-myowin** [pusher/pusher-channels-flutter#41]
As mentioned in title, my backend is the combination of Laravel+Pusher+Echo. I have read the [auth endpoint doc](https://pub.dev/packages/pusher_channels_flutter#authendpoint-string) which refers to https://pusher.com/docs/channels/server_api/authenticating-users/ and I have read that as well. But I still got no idea how to authenticate to my backend to listen to a private channel.

**Comment by gtu-myowin** [comment]
I was getting 403 error while authentication to laravel backend but I have found a solution to connect to a private channel successfully.

I need to add this api route 

```php
Broadcast::routes(['middleware' => ['auth:sanctum']]);
```

as mentioned in [laravel doc](https://laravel.com/docs/9.x/sanctum#authorizing-private-broadcast-channels) but that's not all I have to remove `authEndpoint` from [`pusher.init()`](https://github.com/pusher/pusher-channels-flutter/blob/de1bf5f2d87f72c16e8279caff70feeab6e7a5ff/example/lib/main.dart#L70) method and then handle the authentication in `onAuthorizer` method as mentioned in https://github.com/pusher/pusher-channels-flutter/issues/34#issuecomment-1082805721

Here is the relevant source code.

```dart
class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();

  @override
  void initState() {
    super.initState();

    _pusherConnect();

  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ........
    );
  }

  void _pusherConnect() async {
    SharedPreferences _prefs = await SharedPreferences.getInstance();

    if (_prefs.getString('user') != null) {
      // get encoded user and decode it
      var _usr = json.decode(_prefs.getString('user').toString());
      // convert to user object
      if (_usr != null) {
        User? _user = User.fromJson(_usr);

        try {
          await pusher.init(
            apiKey: 'c8a80c98e5ee7ff9462c',
            cluster: 'ap1',
            onSubscriptionSucceeded: onSubscriptionSucceeded,
            onEvent: onEvent,
            onSubscriptionError: onSubscriptionError,
            onAuthorizer: onAuthorizer,
          );
          await pusher.subscribe(channelName: 'private-App.Models.User.' + _user.id.toString());
          await pusher.connect();
        } catch (e) {
          log("ERROR: $e");
        }
      }
    }
  }

  void onSubscriptionSucceeded(String channelName, dynamic data) {
    log("onSubscriptionSucceeded: $channelName data: $data");
    final me = pusher.getChannel(channelName)?.me;
    log("Me: $me");
  }
  
  void onEvent(PusherEvent event) {
    log("onEvent: $event");
  }

  void onSubscriptionError(String message, dynamic e) {
    log("onSubscriptionError: $message Exception: $e");
  }

  dynamic onAuthorizer(String channelName, String socketId, dynamic options) async {
    String? _token = Provider.of<Auth>(context, listen: false).token;

    var authUrl = appUrl + '/api/broadcasting/auth';
    var result = await post(
      Uri.parse(authUrl),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'Bearer $_token',
      },
      body: 'socket_id=' + socketId + '&channel_name=' + channelName,
    );

    log(result.body);

    return jsonDecode(result.body);
  }
}
```

**Comment by yacinegithub** [comment]
> I was getting 403 error while authentication to laravel backend but I have found a solution to connect to a private channel successfully.
> 
> I need to add this api route 
> 
> ```php
> Broadcast::routes(['middleware' => ['auth:sanctum']]);
> ```
> 
> as mentioned in [laravel doc](https://laravel.com/docs/9.x/sanctum#authorizing-private-broadcast-channels). But that's not all, I have to remove `authEndpoint` from [`pusher.init()`](https://github.com/pusher/pusher-channels-flutter/blob/de1bf5f2d87f72c16e8279caff70feeab6e7a5ff/example/lib/main.dart#L70) method and then handle authentication in `onAuthorizer` method as mentioned in https://github.com/pusher/pusher-channels-flutter/issues/34#issuecomment-1082805721
> 
> Here is the relevant source code.
> 
> ```dart
> class Home extends StatefulWidget {
>   const Home({Key? key}) : super(key: key);
> 
>   @override
>   State<Home> createState() => _HomeState();
> }
> 
> class _HomeState extends State<Home> {
>   PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     _pusherConnect();
> 
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       ........
>     );
>   }
> 
>   void _pusherConnect() async {
>     SharedPreferences _prefs = await SharedPreferences.getInstance();
> 
>     if (_prefs.getString('user') != null) {
>       // get encoded user and decode it
>       var _usr = json.decode(_prefs.getString('user').toString());
>       // convert to user object
>       if (_usr != null) {
>         User? _user = User.fromJson(_usr);
> 
>         try {
>           await pusher.init(
>             apiKey: 'c8a80c98e5ee7ff9462c',
>             cluster: 'ap1',
>             onSubscriptionSucceeded: onSubscriptionSucceeded,
>             onEvent: onEvent,
>             onSubscriptionError: onSubscriptionError,
>             onAuthorizer: onAuthorizer,
>           );
>           await pusher.subscribe(channelName: 'private-App.Models.User.' + _user.id.toString());
>           await pusher.connect();
>         } catch (e) {
>           log("ERROR: $e");
>         }
>       }
>     }
>   }
> 
>   void onSubscriptionSucceeded(String channelName, dynamic data) {
>     log("onSubscriptionSucceeded: $channelName data: $data");
>     final me = pusher.getChannel(channelName)?.me;
>     log("Me: $me");
>   }
>   
>   void onEvent(PusherEvent event) {
>     log("onEvent: $event");
>   }
> 
>   void onSubscriptionError(String message, dynamic e) {
>     log("onSubscriptionError: $message Exception: $e");
>   }
> 
>   dynamic onAuthorizer(String channelName, String socketId, dynamic options) async {
>     String? _token = Provider.of<Auth>(context, listen: false).token;
> 
>     var authUrl = appUrl + '/api/broadcasting/auth';
>     var result = await post(
>       Uri.parse(authUrl),
>       headers: {
>         'Content-Type': 'application/x-www-form-urlencoded',
>         'Authorization': 'Bearer $_token',
>       },
>       body: 'socket_id=' + socketId + '&channel_name=' + channelName,
>     );
> 
>     log(result.body);
> 
>     return jsonDecode(result.body);
>   }
> }
> ```

Thanks, Where we have to put the appkey and the Port number 6001, and do you use the free Laravel  pusher replacement or the paid one ?

**Comment by yacinegithub** [comment]
> @yacinegithub `pusher-channels-flutter` doesn't need those info. You must be confusing with another package. What I have given is a functional code. You can just replace with your pusher credential.

Actually am using the free Laravel pusher replacement which is the laravel websockets package.

**Comment by gtu-myowin** [comment]
@yacinegithub Can you provide the link of the packages you used so that I can understand you better? But normally, host is your domain name e.g; `github.com` is a host. port is what your websocket is running on. See this https://github.com/beyondcode/laravel-websockets/discussions/813 for more detail.

**Comment by yacinegithub** [comment]
> @yacinegithub Can you provide the link of the packages you used so that I can understand you better? But normally, host is your domain name e.g; `github.com` is a host. port is what your websocket is running on. See this https://github.com/beyondcode/laravel-websockets/discussions/813 for more detail.

Yes i use this package mentioned in the link above, the thing I want you to understand is that i am not using the paid pusher, i use the free pusher replacement described in the same package documentation 
https://beyondco.de/docs/laravel-websockets/basic-usage/pusher#:~:text=The%20Laravel%20WebSocket%20Pusher%20replacement,WebSocket%20applications%20with%20one%20server.

**Comment by gtu-myowin** [comment]
Pusher.com has free tier as well. You don't have to pay for a fairly amount. But if you would want to continue with Laravel Websockets, you should read the related documentation and open issues at the related repo because the solutions here won't fit your needs. This is a repo for flutter package of pusher.com

**Comment by benw-pusher** [comment]
I'll close this out as it looks to be related to laravel-websockets and not the flutter repo or Pusher service.
