### ISSUE TITLE
FATAL EXCEPTION: ServerSyncHandler-c90f4948-38f9-4363-943d-0ba5b734ddb8-inner-worker

### ISSUE THREAD

**Issue by sithvothykiv** [pusher/pusher-channels-flutter#50]
Hello, I received this error and the app is crashing.

**E/AndroidRuntime(32333): FATAL EXCEPTION: ServerSyncHandler-c90f4948-38f9-4363-943d-0ba5b734ddb8-inner-worker**
E/AndroidRuntime(32333): Process: com.app.example.client, PID: 32333
E/AndroidRuntime(32333): java.lang.NullPointerException: jwt must not be null
E/AndroidRuntime(32333): 	at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.processSetUserIdJob(ServerSyncHandler.kt:393)
E/AndroidRuntime(32333): 	at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.processJob(ServerSyncHandler.kt:463)
E/AndroidRuntime(32333): 	at com.pusher.pushnotifications.internal.ServerSyncProcessHandler.handleMessage(ServerSyncHandler.kt:504)
E/AndroidRuntime(32333): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32333): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(32333): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(32333): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by fbenevides** [comment]
Hi @sithvothykiv, could you please provide more context? Steps to reproduce would be enough

Thanks!

**Comment by sithvothykiv** [comment]
I solved it.
