### ISSUE TITLE
FlutterActivity incompatible with several dependencies local_auth, flutter_stripe FlutterFragmentActivity

### ISSUE THREAD

**Issue by ilml1** [pusher/pusher-channels-flutter#52]
Hello dear pusher team, 
As mentioned in the [PR](https://github.com/pusher/pusher-channels-flutter/pull/51), There is a fatal crashing error when using this pusher dependency in conjunction with projects that are using plugins that require flutter creators to use FlutterFragmentActivity instead of the standard FlutterActivity.  (local_auth, which is an official flutter team plugin, flutter_stripe, and probably more)
Opened this issue, with the hopes we can have a conversation on the topic and a fix or merge can be implemented soon.

Thanks for your work!

**Comment by ilml1** [comment]
[Pr fixing this issue ](https://github.com/pusher/pusher-channels-flutter/pull/51 )was approved, only needs to be merged now.

**Comment by ilml1** [comment]
[PR was merged](https://github.com/pusher/pusher-channels-flutter/pull/51)

**Comment by nazy61** [comment]
Hi, this issue was fixed 5 days ago but it is yet to reflect on pub.dev. please when can an update on the package be done?
