### ISSUE TITLE
How to listen event from child widget

### ISSUE THREAD

**Issue by gtu-myowin** [pusher/pusher-channels-flutter#55]
Hi,

Thank you for the very handy package. I have one question though. According to [this example code](https://github.com/pusher/pusher-channels-flutter/blob/master/example/lib/main.dart), I have initiated the pusher in my `main.dart` and configured `onEvent` callback.

I need to things on same event on child widget but the task is different. I tried to subscribe to the channel in child widget but it say I cannot subscribe again because it is already subscribed.

How can I perform `onEvent` on child widget again?

Thanks in advance.

**Comment by gtu-myowin** [comment]
I figured it out. First unsubscribe and then re-subscribe 
```dart
await pusher.unsubscribe(channelName: 'my-channel');
await pusher.subscribe(channelName: 'my-channel', onEvent: _onEvent);
```

**Comment by benjamin-tang-pusher** [comment]
Hi, could you describe your use case for changing the callback with the child widget? Does the child widget only get created under a specific condition? Just interested in your use case.

**Comment by gtu-myowin** [comment]
@benjamin-tang-pusher The use cases are

1. I have a chat module in my app 
- I put a chat icon with unread count in `Appbar` of every screen
- when new message comes, I increase the unread count there
I only need to increase the total unread count here

2. Then user would tap that icon
- which lead him to Chat List screen
- on that page I have to increase the unread count on `Appbar` and as well as beside the person's name who sent the message
On this screen, I have to increase both total unread count and each person's unread count. Therefore, the task is different from use case 1 

3. Then user can tap on a person 
- which lead him to Single Chat screen
- on this screen, when event happen, I have to push the new message into the chat so that user can see the message in real time.
Here, the task to do is different too.

I don't think you would expect me to do all of this in main `onEvent` callback, would you?

**Comment by benjamin-tang-pusher** [comment]
Makes sense, thanks for taking to the time to explain. I will close this issue.
