### ISSUE TITLE
socketId

### ISSUE THREAD

**Issue by kwul0208** [pusher/pusher-channels-flutter#56]
I'm new in flutter. How to get socketId? i've try use `final socketId = await pusher.getSocketId();` but I did not know where can I place this. 

I always get error: 
 

> This expression has a type of 'void' so its value can't be used.

thanks..

**Comment by benjamin-tang-pusher** [comment]
I'm getting the same, let me check if we made a mistake with the library.

**Comment by kaushikparmar** [comment]
I'm still seeing this error. getSocketId() returns Future<void>.

Is this fixed?
