### ISSUE TITLE
Port configuration for Laravel Echo

### ISSUE THREAD

**Issue by nicolasvahidzein** [pusher/pusher-channels-flutter#57]
Can we use this with Laravel Echo?

I do not see any port settings in the auth configuration.

The idea is to use it in conjuction with the "laravel_echo" package.

**Comment by benw-pusher** [comment]
Hi, you shouldn't need to set a port to use this library with Pusher Channels - even when using Laravel Echo. Are you using your own custom websocket server?

**Comment by benw-pusher** [comment]
Closing this as I have had no response.
