### ISSUE TITLE
FlutterFragmentActivity crashing application 

### ISSUE THREAD

**Issue by bazl-E** [pusher/pusher-channels-flutter#58]
when i try to integrate local auth (official package from flutter ) i have to change flutter activity to fragment activity and it is causing to crash in devices which supports local auth and pusher not working in non supported device 

W/System.err(21302): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(21302): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
E/AndroidRuntime(21302): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime(21302): Process: com.icodmmp.finwallet, PID: 21302
E/AndroidRuntime(21302): java.lang.NullPointerException
E/AndroidRuntime(21302): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback(PusherChannelsFlutterPlugin.kt:90)
E/AndroidRuntime(21302): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onConnectionStateChange(PusherChannelsFlutterPlugin.kt:209)
E/AndroidRuntime(21302): 	at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:166)
E/AndroidRuntime(21302): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
E/AndroidRuntime(21302): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(21302): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(21302): 	at java.lang.Thread.run(Thread.java:919)
W/odmmp.finwalle(21302): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/odmmp.finwalle(21302): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/odmmp.finwalle(21302): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/odmmp.finwalle(21302): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/ActivityThread(21302): SCHED: com.icodmmp.finwallet/io.flutter.embedding.android.FlutterFragmentActivity [82, r=1024ms, a=214ms, w=35451ms]
I/Process (21302): Sending signal. PID: 21302 SIG: 9
Lost connection to device.

**Comment by KristupasKuras** [comment]
I'm having the same issue event with 2.0.1 :/ Any ideas?

**Comment by benw-pusher** [comment]
Could you share more details about the changes you have made, perhaps sharing your code for review?

**Comment by benw-pusher** [comment]
It would be good to get a small replication app if possible, or the code that is being executed when your app encounters this error. We can then look at replication and troubleshooting.

**Comment by geldartz** [comment]
facing same issue :(

**Comment by keanyee** [comment]
facing the same issue with Android 12.0. 

E/AndroidRuntime( 9649): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime( 9649): Process: com.example.fetch_frontend, PID: 9649
E/AndroidRuntime( 9649): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pusher.client.channel.User.getId()' on a null object reference
E/AndroidRuntime( 9649): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onUsersInformationReceived(PusherChannelsFlutterPlugin.kt:272)
E/AndroidRuntime( 9649): 	at com.pusher.client.channel.impl.PresenceChannelImpl.handleSubscriptionSuccessfulMessage(PresenceChannelImpl.java:126)
E/AndroidRuntime( 9649): 	at com.pusher.client.channel.impl.PresenceChannelImpl.onMessage(PresenceChannelImpl.java:58)
E/AndroidRuntime( 9649): 	at com.pusher.client.channel.impl.ChannelManager.onMessage(ChannelManager.java:116)
E/AndroidRuntime( 9649): 	at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:177)
E/AndroidRuntime( 9649): 	at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:27)
E/AndroidRuntime( 9649): 	at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:261)
E/AndroidRuntime( 9649): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
E/AndroidRuntime( 9649): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime( 9649): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime( 9649): 	at java.lang.Thread.run(Thread.java:1012)
I/Process ( 9649): Sending signal. PID: 9649 SIG: 9

**Comment by benw-pusher** [comment]
We haven't been able to replicate this one and a replication sample hasn't been provided so we will have to close this out. FI you need further support please contact us at https://support.pusher.com/hc/en-us/requests/new
