### ISSUE TITLE
Usable with soketi websocket?

### ISSUE THREAD

**Issue by combi-35** [pusher/pusher-channels-flutter#66]
Can I use this package when using a Soketi websocket with a Laravel backend?
So far I am not able to connect.

I also need to change ports, but this package does not have an option to do so.

Any help is appreciated as this is holding us back.

**Comment by benw-pusher** [comment]
This package is designed for use with Pusher Channels and does not support connecting to other servers such as Soketi server.

**Comment by combi-35** [comment]
@benw-pusher Sad to hear as soketi is also using Pusher Protocol.

I have forked the project and tried adding host and port parameters but it seems to have no effect.
I would really appreciate help as I don't know how to proceed. I can also tip you some coffees 😃

**Comment by WebMad** [comment]
> @benw-pusher Sad to hear as soketi is also using Pusher Protocol.
> 
> I have forked the project and tried adding host and port parameters but it seems to have no effect. I would really appreciate help as I don't know how to proceed. I can also tip you some coffees 😃

Hi! Have you solved this issue? Can share your origins?

**Comment by adnweedon** [comment]
> This package is designed for use with Pusher Channels and does not support connecting to other servers such as Soketi server.

@benw-pusher All three of the packages this wraps support setting the host, so it feels inconsistent that this package doesn't also - I was just wondering if there was any chance this feature could be reconsidered? 🙂
