### ISSUE TITLE
Execution failed for task ':pusher_channels_flutter:compileDebugKotlin'.

### ISSUE THREAD

**Issue by ultramegagood** [pusher/pusher-channels-flutter#69]
Running Gradle task 'assembleDebug'...
e: /Users/madiyar/development/flutter/.pub-cache/hosted/pub.dartlang.org/pusher_channels_flutter-2.0.0/android/src/main/kotlin/com/pusher/channels_flutter/PusherChannelsFlutterPlugin.kt: (25, 7): Redeclaration: PusherChannelsFlutterPlugin
e: /Users/madiyar/development/flutter/.pub-cache/hosted/pub.dartlang.org/pusher_channels_flutter-2.0.1/android/src/main/kotlin/com/pusher/channels_flutter/PusherChannelsFlutterPlugin.kt: (25, 7): Redeclaration: PusherChannelsFlutterPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pusher_channels_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

who got this error please help

**Comment by benw-pusher** [comment]
Have you tried to clean project and then rebuild? 
If you are still encountering the issue could you try one of the suggested option to get more log info and share the output with us? 

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

**Comment by benjamin-tang-pusher** [comment]
Hi, we need reproduction steps in order to troubleshoot this. As there's been no response to this issue, I will close it.
