### ISSUE TITLE
App key websoket_app_key not in this cluster. Did you forget to specify the cluster?

### ISSUE THREAD

**Issue by hmbadhon** [pusher/pusher-channels-flutter#71]
[log] Connection: CONNECTING
[log] onError: App key websoket_app_key not in this cluster. Did you forget to specify the cluster? code: 4001 exception: <PusherSwift.PusherError: 0x600003fd8750>
[log] Connection: DISCONNECTED
[log] Connection: RECONNECTING
[log] Connection: CONNECTING
[log] onError: App key websoket_app_key not in this cluster. Did you forget to specify the cluster? code: 4001 exception: <PusherSwift.PusherError: 0x600003fdc090>
[log] Connection: DISCONNECTED
[log] Connection: RECONNECTING
[log] Connection: CONNECTING
[log] onError: App key websoket_app_key not in this cluster. Did you forget to specify the cluster? code: 4001 exception: <PusherSwift.PusherError: 0x600003fdc120>
[log] Connection: DISCONNECTED
[log] Connection: RECONNECTING
[log] Connection: CONNECTING
[log] onError: App key websoket_app_key not in this cluster. Did you forget to specify the cluster? code: 4001 exception: <PusherSwift.PusherError: 0x600003fdcae0>

**Comment by hmbadhon** [comment]
Used below this to connect with pusher....

void connectSocket() async {
    try {
      await pusher.init(
          apiKey: 'websoket_app_key',   //PUSHER_APP_KEY
          cluster: 'mt1',   //PUSHER_APP_CLUSTER
          useTLS: false,
          authEndpoint: "http://{$URL}/api/v1/broadcasting/auth",
          onConnectionStateChange: onConnectionStateChange,
          onError: onError,
          onSubscriptionSucceeded: onSubscriptionSucceeded,
          onEvent: onEvent,
          onSubscriptionError: onSubscriptionError,
          onDecryptionFailure: onDecryptionFailure,
          onMemberAdded: onMemberAdded,
          onMemberRemoved: onMemberRemoved,
          onAuthorizer: onAuthorizer);
      await pusher.subscribe(channelName: 'my-channel');
      await pusher.connect();
    } catch (e) {
      log("ERROR: $e");
    }
  }

**Comment by benw-pusher** [comment]
When you create an app in the Pusher dashboard you can select a cluster, did you select the main cluster? The cluster you specify in the code must match the cluster of the app you created - the error you are experiencing indicates this has not been set correctly.

**Comment by hmbadhon** [comment]
so i'm using laravel websocket which is a pusher wrapper but free to use. Can i able to use this package for that?

**Comment by benw-pusher** [comment]
It is not possible to use this library with laravel websocket, this library is designed for use with the official Channels service.
