### ISSUE TITLE
connect with two or more channel

### ISSUE THREAD

**Issue by kwul0208** [pusher/pusher-channels-flutter#73]
how to connect with two channel pusher in flutter? I already have a flutter which is already connected to one channel

**Comment by benw-pusher** [comment]
Are you looking to subscribe to two channels, for example 'chat-ben' and 'chat-andrea'? To do this you would simply subscribe to another channel using the standard subscribe code - 

final benChannel = await pusher.subscribe(channelName: "chat-ben");
final andreaChannel = await pusher.subscribe(channelName: "chat-andrea");
