### ISSUE TITLE
Web throw PlatformException after connected.

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [pusher/pusher-channels-flutter#82]
<img width="1046" alt="Screenshot 2022-11-08 at 10 39 53 AM" src="https://user-images.githubusercontent.com/46706152/200496446-1aeb8528-ef97-46e4-9a7f-0d3f8441a9ed.png">

**Comment by chaithanyaangalagunta** [comment]
Same issue for me also,  Havent found a fix yet.

**Comment by ebnibrahem** [comment]
Same issue for me too.

**Comment by benjamin-tang-pusher** [comment]
The "Connection not authorized within timeout" is because you enabled "enable authorized connections" in your Pusher dashboard, but your app isn't subscribing to a private channel. If you subscribe to a private channel, does this error still appear?

**Comment by benw-pusher** [comment]
I believe you can prevent this error by removing the `onError` callback in the Pusher Init function. It appears this also unintentionally invokes native Dart error handling - removing the callback prevents this from occurring.
