### ISSUE TITLE
authParams for Android & iOS

### ISSUE THREAD

**Issue by appcapsergen** [pusher/pusher-channels-flutter#84]
For my project, I'm using [`pusher_client`](https://pub.dev/packages/pusher_client/changelog) to work with pusher.
Now I discovered this package, made by you, the people of pusher itself, but `authParams` isn't supported on Android and iOS.
This does work with [`pusher_client`](https://pub.dev/packages/pusher_client/changelog) so I'll have to continue using that, since I need this for my project. I'd love to see it implemented.

My request is to implement authParams for Android and iOS, but also the question of when will this happen/is there a plan for this to be implemented?

**Comment by benjamin-tang-pusher** [comment]
Hi, yes our engineering is aware of the demand for this parameter. They're currently prioritising it with our freelancer who works on this library, but we cannot commit to a timeline for it. Thanks for letting us know anyway, we will add this to our list of feature requests. When we add this parameter, we will add it to the readme.
