### ISSUE TITLE
Could not parse eventName to subscribe() method

### ISSUE THREAD

**Issue by douagnobed** [pusher/pusher-channels-flutter#89]
Hello, thank you for publishing this package. I'm so grateful to use this package. But issue is that, the subscribe method does not have event name param to specify.

**Comment by douagnobed** [comment]
So how can I specify the event name for the channel to which I am subscribing?

**Comment by benw-pusher** [comment]
When subscribing to a channel the client will receive all events broadcast on that channel. You can use the onEvent to handle such events, inckuding inspecting the event payload for the channel and event names that were present on the event and handle accordingly. 
See https://github.com/pusher/pusher-channels-flutter#pusherevent for details on the event payload.
