### ISSUE TITLE
PlatformException(PusherChannels, null, null, null)

### ISSUE THREAD

**Issue by Codesait** [pusher/pusher-channels-flutter#9]
pusher not connecting plus bad documentation.

**Comment by Frogperson** [comment]
I'm getting a similar issue, but only when building with --release.
Building in debug mode works perfectly for me on both Android and Web.

**Comment by Codesait** [comment]
> 

Could you share your implementation please?

**Comment by Frogperson** [comment]
> > 
> 
> Could you share your implementation please?

Sure, but it's basically just a stripped down version of the example here https://github.com/pusher/pusher-channels-flutter/tree/master/example

Here's a slightly modified copy of my code. Let me know if you have any questions
```import 'package:http/http.dart';
import 'package:http/http.dart';
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart';

class Pusher {
  static PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
  static const authURL = "https://example.com/websocketAuth";

  void connect(List<String> channelIds, void Function(PusherEvent event) onEvent) async {
    await pusher.init(
      apiKey: '<apikey>',
      cluster: '<cluster>',
      useTLS: true,
      onEvent: onEvent,
      onAuthorizer: onAuthorizer,
      authEndpoint: authURL,
    );
    for (var channelId in channelIds) {
      await pusher.subscribe(channelName: 'presence-' + channelId);
    }
    await pusher.connect();
  }

  dynamic onAuthorizer(String channelName, String socketId, dynamic options) async {
    return await post(
      Uri.parse(authURL),
      headers: {"Content-Type": "application/x-www-form-urlencoded"},
      body: "socket_id=" + socketId + "&channel_name=" + channelName,
    );
  }
}
```
If I run this through the debugger in IntelliJ, it seems to work perfectly, and will connect and authenticate correctly. But as soon as I try to run a release build, it still connects, but won't authenticate and throws: 
this error on Android `PlatformException(PusherChannels, null, null, null)`
and this error on Web `Uncaught TypeError: J.getInterceptor$x(...).get$current is not a function`

**Comment by ViniciusDBarth** [comment]
I'm having the same problem.

**Comment by Frogperson** [comment]
Just tested this again on version 1.0.3-dev.6 and am still running into issues when building with --profile or --release. --debug still seems to work fine.
However, I'm getting a slightly different error, so looks like some progress has been made!
Here's the current error I'm getting (in web, haven't had a chance to test android yet) in case it will help:
```
Uncaught TypeError: Qt.createAuthorizer(...).authorize is not a function
    at e.authorize (private_channel.ts:18:23)
    at e.authorize (presence_channel.ts:29:20)
    at e.subscribe (channel.ts:101:10)
    at t.subscribe (pusher.ts:226:15)
    at t.subscribeAll (pusher.ts:213:14)
    at pusher.ts:115:12
    at e.t.emit (dispatcher.ts:76:25)
    at e.updateState (connection_manager.ts:364:12)
    at Object.connected (connection_manager.ts:296:14)
    at e (connection_manager.ts:167:45)
    ```

**Comment by proggen-com** [comment]
Can you provide a bit more context on how you've implemented the authorizer when initializing Pusher ?

**Comment by Frogperson** [comment]
You can see a stripped down version of my code in my comment here https://github.com/pusher/pusher-channels-flutter/issues/9#issuecomment-1013764670

My onAuthorizer() sends an http post to the authURL, which returns json with "auth" and "channel_data" as the response

**Comment by proggen-com** [comment]
I think you can get this to work using something like the following code:

```
import 'dart:convert';
import 'package:http/http.dart';

dynamic onAuthorizer(String channelName, String socketId, dynamic options) async {
    var authURL = "http://<YOUR AUTH ENDPOINT>:5000/pusher/auth";
    var result = await post(
      Uri.parse(authURL),
      headers: {"Content-Type": "application/x-www-form-urlencoded"},
      body: "socket_id=" + socketId + "&channel_name=" + channelName,
    );
    return jsonDecode(result.body);
  }
```

**Comment by Frogperson** [comment]
Forgive me if I'm missing something, but the only change I'm seeing there is returning `jsonDecode(result.body)` rather than just `result`.
I actually already do this, but accidentally cut it out when simplifying the code for pasting here. I have a custom post method which automatically handles cookies for me (for use on Android), and my method does already return a decoded result.body.

Again, I have no problems when building in debug mode. This error only pops up when building in --profile or --release, so I don't believe it's an issue with my code.
Here's the stacktrace I'm receiving in my Chrome dev console:
```
Uncaught TypeError: Qt.createAuthorizer(...).authorize is not a function
    at e.authorize (private_channel.ts:18:23)
    at e.authorize (presence_channel.ts:29:20)
    at e.subscribe (channel.ts:101:10)
    at t.subscribe (pusher.ts:226:15)
    at t.subscribeAll (pusher.ts:213:14)
    at pusher.ts:115:12
    at e.t.emit (dispatcher.ts:76:25)
    at e.updateState (connection_manager.ts:364:12)
    at Object.connected (connection_manager.ts:296:14)
    at e (connection_manager.ts:167:45)
e.authorize	     @ private_channel.ts:18
e.authorize      @ presence_channel.ts:29
e.subscribe	     @ channel.ts:101
t.subscribe	     @ pusher.ts:226
t.subscribeAll	 @ pusher.ts:213
(anonymous)	     @ pusher.ts:115
t.emit	         @ dispatcher.ts:76
e.updateState	 @ connection_manager.ts:364
connected	     @ connection_manager.ts:296
e	             @ connection_manager.ts:167
o	             @ cached_strategy.ts:83
(anonymous)	     @ first_connected_strategy.ts:24
(anonymous)	     @ best_connected_ever_strategy.ts:33
c	             @ sequential_strategy.ts:44
(anonymous)	     @ sequential_strategy.ts:114
(anonymous)	     @ transport_strategy.ts:74
t.finish	     @ index.ts:86
onMessage	     @ index.ts:58
t.emit	         @ dispatcher.ts:76
e.onMessage	     @ transport_connection.ts:187
socket.onmessage @ transport_connection.ts:205
```
Hopefully it helps!

**Comment by JimmyTai** [comment]
After investigation and try and error. I found a solution.

- Change **"Authorizer"** class declaration like the code below in options.dart, Javascript part would call **"authorize"** function successfully.

```
typedef AuthorizeFunc = void Function(
    String socketId, AuthorizerCallback callback);

@anonymous
@JS()
class Authorizer {
  external set authorize(AuthorizeFunc v);
  external AuthorizeFunc get authorize;
  external factory Authorizer({AuthorizeFunc authorize});
}
```

- And implements **"onAuthorizer"** function in pusher_channels_flutter_web.dart like the code below.
```
Authorizer onAuthorizer(Channel channel, AuthorizerOptions options) {
    return Authorizer(
      authorize: allowInterop((socketId, callback) async {
        try {
          var authData = await methodChannel!.invokeMethod('onAuthorizer', {
            'socketId': socketId,
            'channelName': channel.name,
            'options': AuthorizerOptions.toMap(options),
          });
          callback(
              null,
              AuthData(
                  auth: authData['auth'],
                  channel_data: authData['channel_data'],
                  shared_secret: authData['shared_secret']));
        } catch (e) {
          callback(PusherError(e.toString(), -1), AuthData(auth: ''));
        }
      }),
    );
  }
```

This flutter web SDK still contains some sort of issues and data parsing issues. I will prepare a PR for all issues I met.
