### ISSUE TITLE
Bind Pusher Event

### ISSUE THREAD

**Issue by eggywardani** [pusher/pusher-channels-flutter#92]
How to bind or listen events from the pusher ?

**Comment by eggywardani** [comment]
Done

**Comment by ZakwanIbrahim3321** [comment]
can you attach code snippet, how did you bind events

**Comment by mirzobedil** [comment]
> can you attach code snippet, how did you bind events

I used this method and it worked)

```
  void onEvent(PusherEvent event) {
    final eventHandler = GlobalEventHandler();
    eventHandler.emit(event.eventName, event.data);
  }
```

```
class GlobalEventHandler {
  static final GlobalEventHandler _instance = GlobalEventHandler._internal();

  factory GlobalEventHandler() {
    return _instance;
  }

  GlobalEventHandler._internal();

  final Map<String, Function> _events = {};

  void on(String eventName, Function callback) {
    _events[eventName] = callback;
  }

  void off(String eventName) {
    _events.remove(eventName);
  }

  void emit(String eventName, dynamic data) {
    if (_events.containsKey(eventName)) {
      _events[eventName]!(data);
    }
  }
}
```

**Comment by ZakwanIbrahim3321** [comment]
> > can you attach code snippet, how did you bind events
> 
> I used this method and it worked)
> 
> ```
>   void onEvent(PusherEvent event) {
>     final eventHandler = GlobalEventHandler();
>     eventHandler.emit(event.eventName, event.data);
>   }
> ```
> 
>  ```
> class GlobalEventHandler {
>   static final GlobalEventHandler _instance = GlobalEventHandler._internal();
> 
>   factory GlobalEventHandler() {
>     return _instance;
>   }
> 
>   GlobalEventHandler._internal();
> 
>   final Map<String, Function> _events = {};
> 
>   void on(String eventName, Function callback) {
>     _events[eventName] = callback;
>   }
> 
>   void off(String eventName) {
>     _events.remove(eventName);
>   }
> 
>   void emit(String eventName, dynamic data) {
>     if (_events.containsKey(eventName)) {
>       _events[eventName]!(data);
>     }
>   }
> }
> ```

thanks buddy
