### ISSUE TITLE
java.net.UnknownHostException - Lock Screen Reconnect | Android

### ISSUE THREAD

**Issue by manuduxi** [pusher/pusher-channels-flutter#94]
My Pusher connection works fine when the app is open or minimized in background, but when I lock the phone, the connection breaks after about ~3 Minutes, Pusher then tries to reconnect but throws the following Error:

I/flutter ( 5954): Connection: RECONNECTING
I/flutter ( 5954): Connection: CONNECTING
W/User    ( 5954): An exception was thrown by the websocket
I/flutter ( 5954): Connection: RECONNECTING
I/flutter ( 5954): onError: An exception was thrown by the websocket code: null exception: java.net.UnknownHostException: Unable to resolve host "ws-eu.pusher.com": No address associated with hostname

until it stops trying.
So when I unlock the phone, the connection is still lost.

Version: 2.1.0
Code:

```dart
class PusherNotifier extends AutoDisposeAsyncNotifier<PusherChannelsFlutter> {
  Future<PusherChannelsFlutter> _init() async {
    PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
    final AppUser? appUser = ref.watch(userProvider);

    try {
      await pusher.init(
        apiKey: dotenv.env['PUSHER_APP_KEY']!,
        cluster: dotenv.env['PUSHER_APP_CLUSTER']!,
        onEvent: onEvent,
        onConnectionStateChange: onConnectionStateChange,
        onError: onError,
      );

      String myChannel = 'myChannel';

      await pusher.subscribe(channelName: myChannel);
      await pusher.connect();
    } catch (e) {
      print("ERROR: $e");
    }

    return pusher;
  }

  @override
  FutureOr<PusherChannelsFlutter> build() async {
    return _init();
  }

  void onEvent(PusherEvent event) {
    print("onEvent: $event");
    switch (event.eventName) {
      case 'refreshChat':
        ref.read(messageNotifierProvider.notifier).newEvent(event);
        break;
    }
  }

  void onError(String message, int? code, dynamic e) {
    print("onError: $message code: $code exception: $e");
  }

  void onConnectionStateChange(dynamic currentState, dynamic previousState) {
    print("Connection: $currentState");
  }
}
```

Has someone experienced this already or is there something wrong with my Code?

**Comment by luisfelipeas5** [comment]
We launched a new version today and this crash started to happen in production. It's interesting: this is the first build that is built using Flutter v3.7.
@manuduxi , which flutter version are you using?

**Comment by luisfelipeas5** [comment]
This is happening with us too. We recently put a custom log inside `onError` callback of `PusherChannelsFlutter.init` and we detecting this issue on production and with one day of the new version, this issue was registered 143 times (affecting 15 users).

**Comment by benw-pusher** [comment]
Thanks for the update. Have you set any special configuration for the app to run in the background - my understanding was that the app would pause when in the background or screen is locked, so the library wouldn't be retrying the connection. 
In any case, monitoring the app lifecycle seems like a sensible solution.
