### ISSUE TITLE
FATAL EXCEPTION: pusher-java-client eventQueue

### ISSUE THREAD

**Issue by ziagit** [pusher/pusher-channels-flutter#97]
I used this package in my last projects without issue, but in new Flutter app when `pusher.connect` calls the app crashes and I get the following errors
```
Connection: CONNECTING
[ +940 ms] I/flutter (20075): Connection: CONNECTED
[+1002 ms] E/AndroidRuntime(20075): FATAL EXCEPTION: pusher-java-client eventQueue
[        ] E/AndroidRuntime(20075): Process: com.exptradies.business, PID: 20075
[        ] E/AndroidRuntime(20075): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String
com.pusher.client.channel.impl.message.AuthResponse.getChannelData()' on a null object reference
[        ] E/AndroidRuntime(20075):     at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:84)
[        ] E/AndroidRuntime(20075):     at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:101)
[        ] E/AndroidRuntime(20075):     at
com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0$com-pusher-client-channel-impl-ChannelManager(ChannelManager.java:134)
[        ] E/AndroidRuntime(20075):     at com.pusher.client.channel.impl.ChannelManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
[        ] E/AndroidRuntime(20075):     at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
[        ] E/AndroidRuntime(20075):     at com.pusher.client.util.Factory$$ExternalSyntheticLambda0.run(Unknown Source:2)
[        ] E/AndroidRuntime(20075):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(20075):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(20075):     at java.lang.Thread.run(Thread.java:923)
[ +315 ms] I/Process (20075): Sending signal. PID: 20075 SIG: 9
[ +251 ms] Service protocol connection closed.
[        ] Lost connection to device.
```
Connection state shows that it gets connect, after connected crashes.
any help appreciated.

**Comment by tegkev** [comment]
Can you show how you implement your init ?

**Comment by AbdllahMohamed** [comment]
await pusher.init(
        apiKey: '81d95509077b9f552e664a4',
        cluster: 'mt1',
        onConnectionStateChange: onConnectionStateChange,
        onError: onError,
        onSubscriptionSucceeded: onSubscriptionSucceeded,
        onEvent: onEvent,
        onSubscriptionError: onSubscriptionError,
        onDecryptionFailure: onDecryptionFailure,
        onMemberAdded: onMemberAdded,
        onMemberRemoved: onMemberRemoved,
        onSubscriptionCount: onSubscriptionCount,
        authEndpoint: "$baseurl/broadcasting/auth",
        onAuthorizer: onAuthorizer,
        authParams: {
          'headers': {'Authorization': '${CacheHelper.getData(key: 'token')}'}
        },
      );
      await pusher.subscribe(
          channelName:
              'presence-chat.${widget.confirmDigitalOrderDetailsModel.id}');

      await pusher.connect();

this is my init i have same issue

**Comment by benjamin-tang-pusher** [comment]
I can see in the error message: `...AuthResponse.getChannelData()' on a null object reference`.

Does the auth request from the client hit your backend auth endpoint? What is the auth response from your server (you can delete any sensitive info)?

**Comment by benw-pusher** [comment]
I'll close this out as we haven't had a response yet - if you need anything further please contact us at https://support.pusher.com/hc/en-us/requests/new
